client_config_backend: settings
client_config:
  client_id: 1097094056208-lelag11gg7velq42ivha0k3l678po7ed.apps.googleusercontent.com
  client_secret: mWTVfzh1DcHglJBy1Em0vSZ_

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
