# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pickle_basename',
            field=models.CharField(max_length=1000, null=True, verbose_name='pickle_path'),
        ),
    ]
